# Generated by Django 5.2.12 on 2026-03-26 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku_prefix", models.CharField(max_length=20)),
                (
                    "standard_sizes",
                    models.JSONField(
                        default=list,
                        help_text='JSON array of standard sizes/units, e.g. ["small", "medium"] or ["100mm", "200mm"]',
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(help_text="e.g. units, kg, rolls", max_length=50),
                ),
                (
                    "preferred_storage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("humidity_controlled", "Humidity Controlled"),
                            ("normal", "Normal"),
                        ],
                        help_text="Preferred room type for storing this item",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Inventory Type",
                "verbose_name_plural": "Inventory Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StorageSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("humidity_controlled", "Humidity Controlled"),
                            ("normal", "Normal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("shelf_label", models.CharField(max_length=100)),
                (
                    "max_capacity",
                    models.PositiveIntegerField(help_text="Maximum capacity in units"),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Storage Space",
                "verbose_name_plural": "Storage Spaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "inventory_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.inventorytype",
                    ),
                ),
                (
                    "storage_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.storagespace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["inventory_type__name", "size"],
                "unique_together": {("inventory_type", "size", "storage_space")},
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("add", "Add Stock"),
                            ("use", "Use Stock"),
                            ("adjust", "Adjust"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_changed",
                    models.IntegerField(
                        help_text="Positive for additions, negative for usage/reductions"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, verbose_name="Reason / Notes")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transaction",
                "verbose_name_plural": "Stock Transactions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
